PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX : <http://myWikiTax.de/> 
SELECT ?top1name ?top2name ?name
WHERE {
    ?cl :name ?root .
    ?cl :hasSubclassifier ?topclassifier1 .
    ?cl :hasSubclassifier ?topclassifier2 .
    
    FILTER EXISTS{
        ?topclassifier1 :hasSubclassifier*/:classifies ?entity .
        ?topclassifier2 :hasSubclassifier*/:classifies ?entity .
    }
    FILTER NOT EXISTS{ ?topclassifier1 :hasSubclassifier* ?topclassifier2 . }
    FILTER NOT EXISTS{ ?topclassifier2 :hasSubclassifier* ?topclassifier1 . }
    
    ?topclassifier1 :name ?top1name .
    ?topclassifier2 :name ?top2name .
    FILTER(?top1name < ?top2name && (?top1name!="Data modeling languages"||?top2name!="Markup languages"))
    ?entity :name ?name .
}
ORDER BY ?topclassifier1name ?topclassifier2name