PREFIX : <http://myWikiTax.de/> 
SELECT 
?cname 
?depth
(COUNT(?entity) as ?NumberOfEntities)
(COUNT(?subclassifier) as ?NumberOfSubclassifiers)
(?NumberOfEntities + ?NumberOfSubclassifiers as ?howmany)
WHERE {
	?classifier :depth ?depth .
	?classifier :name ?cname .
	
	{SELECT ?classifier ?entity
	WHERE{
		?classifier :classifies ?entity .
	}
	}
	
	UNION
	
	{SELECT ?classifier ?subclassifier
	WHERE{
		?classifier :hasSubclassifier ?subclassifier .
	}
	}
}
GROUP BY ?cname ?depth
HAVING (?howmany < ?n)
ORDER BY ASC (?depth)