PREFIX : <http://myWikiTax.de/> 
SELECT ?cname  
?depth
(COUNT(?dclassifier) as ?howManyDistantTypes) 
(COUNT(?rclassifier) as ?howManyReachableTypes) ((?howManyDistantTypes-?howManyReachableTypes) as ?difference) 

WHERE {
	?classifier :name ?cname .
    ?classifier :depth ?depth .
    
    FILTER EXISTS{
        ?cl :name "Computer_languages" .
        ?classifier :isA* ?cl . 
    }
    
    {SELECT DISTINCT ?classifier ?dclassifier
    WHERE {
        ?classifier :hasCategory ?dclassifier .
        FILTER NOT EXISTS{
            ?classifier :isA ?classifier2 .
            ?classifier2 :name ?dclassifier .
		}
    }
    }
	UNION
	
	{SELECT DISTINCT ?classifier ?rclassifier
    WHERE {
        ?classifier :hasCategory ?rclassifier .
        ?classifier :isA ?classifier2 .
        ?classifier2 :name ?rclassifier .
    }
    }
}
GROUP BY ?cname ?depth
HAVING (?difference > 0 && ?howManyReachableTypes > 0)
ORDER BY ASC (?difference)