PREFIX : <http://myWikiTax.de/> 
SELECT ?iname  (COUNT(?dclassifier) as ?howManyDistantTypes) (COUNT(?rclassifier) as ?howManyReachableTypes) ((?howManyDistantTypes-?howManyReachableTypes) as ?difference) 
WHERE {

    {SELECT DISTINCT ?entity ?dclassifier
    WHERE {
        ?entity ^:classifies ?dclassifier .
        
        FILTER NOT EXISTS{ 
			?cl :name ?root .
			?cl :hasSubclassifier* ?dclassifier .
		}
    }
    }
	UNION
	{SELECT DISTINCT ?entity ?rclassifier
    WHERE {
        ?entity ^:classifies ?rclassifier . 
        ?cl :name ?root .
		?cl :hasSubclassifier* ?rclassifier .
    }
    }
	?entity :name ?iname .
    FILTER EXISTS{
        ?classifier :classifies ?entity .
        ?cl :name ?root .
		?cl :hasSubclassifier* ?classifier .
    }
}
GROUP BY ?iname
HAVING(?difference>0 && ?howManyReachableTypes>0)
ORDER BY ?iname