PREFIX : <http://myWikiTax.de/>
SELECT ?iname  (COUNT(?dclassifier) as ?howManyDistantTypes) (COUNT(?rclassifier) as ?howManyReachableTypes) ((?howManyDistantTypes-?howManyReachableTypes) as ?difference)
WHERE {
	?entity :name ?iname .
	FILTER EXISTS{
        ?classifier ^:instanceOf ?entity .
        ?cl :name "Computer_languages" .
        ?classifier :isA* ?cl .
    }

    {SELECT DISTINCT ?entity ?dclassifier
    WHERE {
      ?entity :hasCategory ?dclassifier .

      FILTER NOT EXISTS{
         ?cl :name "Computer_languages" .
         ?cl ^:hasCategory* ?dclassifier .
      }
   }
   }
   UNION
   {SELECT DISTINCT ?entity ?rclassifier
    WHERE {
        ?entity :instanceOf ?rclassifier .
        ?cl :name "Computer_languages" .
        ?rclassifier :isA*  ?cl.
        FILTER NOT EXISTS {
            ?rclassifier :marked "false".
        }
    }
    }

}
GROUP BY ?iname
ORDER BY ?iname
