PREFIX : <http://myWikiTax.de/> 
SELECT ?cname  (COUNT(?dclassifier) as ?howManyDistantTypes) (COUNT(?rclassifier) as ?howManyReachableTypes) ((?howManyDistantTypes-?howManyReachableTypes) as ?difference) ?depth
WHERE {
	?classifier :name ?cname .
    ?classifier :depth ?depth .
    
    FILTER EXISTS{
        ?cl :name ?root .
        ?cl :hasSubclassifier* ?classifier . 
    }
    
    {SELECT DISTINCT ?classifier ?dclassifier
    WHERE {
        ?classifier ^:hasSubclassifier ?dclassifier .
        FILTER NOT EXISTS{
            ?cl :name ?root .
			?cl :hasSubclassifier* ?dclassifier .
		}
    }
    }
	UNION
	
	{SELECT DISTINCT ?classifier ?rclassifier
    WHERE {
        ?classifier ^:hasSubclassifier ?rclassifier .
        ?cl :name ?root .
		?cl :hasSubclassifier* ?rclassifier .
    }
    }
}
GROUP BY ?cname ?depth
HAVING (?difference > 0 && ?howManyReachableTypes > 0)
ORDER BY ASC (?depth)