PREFIX : <http://myWikiTax.de/>
DELETE {?instance :instanceOf ?c}
WHERE{
   {SELECT DISTINCT ?instance ?c
   WHERE {
      ?instance :instanceOf ?c.
      ?instance :relevant "false".
   }
   }
   FILTER(regex(STR(?instance), "Instance"))
}
