PREFIX : <http://myWikiTax.de/>
DELETE {?c1 :isA ?c2}
WHERE{
   {SELECT DISTINCT ?c1 ?c2
   WHERE {
      ?c1 :isA ?c2.
      FILTER EXISTS {
         ?c1 :relevant "false".
      }
      FILTER EXISTS {
         ?c1 :isA* ?r.
         ?r :name "Computer_languages".
      }
      FILTER(regex(STR(?c1), "Classifier")).
   }
   }
}
