PREFIX : <http://myWikiTax.de/>
DELETE {?c1 :isA ?c2}
WHERE{
   ?c1 :name ?name.
   FILTER EXISTS {
      ?c1 :isA* ?r.
      ?r :name "Computer:languages".
   }
   FILTER(regex(STR(?c1), "Classifier")).
}
