PREFIX : <http://myWikiTax.de/>
INSERT {
   ?entity :instanceOf ?superclassifier.
   ?entity :hasCategory ?supername.
}
WHERE{
   ?oldclassifier :name ?name .
   ?oldclassifier :isA ?superclassifier .
   ?entity :instanceOf ?oldclassifier .
   ?superclassifier :name ?supername.
}
