PREFIX : <http://myWikiTax.de/>
INSERT {  ?entity :instanceOf ?superclassifier. }
WHERE{
   ?oldclassifier :name ?name .
   ?oldclassifier :isA ?superclassifier .
   ?entity :instanceOf ?oldclassifier .
}
