PREFIX : <http://myWikiTax.de/>
DELETE {
   ?instance :instanceOf ?classifier.
}
WHERE{
   ?classifier :name ?name.
   ?instance :instanceOf ?classifier.
   ?classifier :relevant "false".
   FILTER(regex(STR(?classifier), "Classifier")).
}
