PREFIX : <http://myWikiTax.de/> 
DELETE { ?type :classifies ?entity }
WHERE {  
    ?type :hasSubclassifier+ ?subtype .
    ?type :classifies ?entity .
    ?subtype :classifies ?entity . 
	?entity :name ?entityname .
	?type :name ?typename .
	?subtype :name ?subtypename .
}