PREFIX : <http://myWikiTax.de/>
DELETE {
   ?instance :instanceOf ?classifier.
   ?classifier :isA ?c2.
}
WHERE{
   ?classifier :relevant "false".
   FILTER(regex(STR(?classifier), "Classifier")).
   ?instance :instanceOf ?classifier.
   ?classifier :isA ?c2.

}
