PREFIX : <http://myWikiTax.de/> 
DELETE { ?superclassifier :hasSubclassifier ?subclassifier }
WHERE {
    ?superclassifier :hasSubclassifier ?subclassifier . 
    ?superclassifier :hasSubclassifier+ ?classifier .
    ?classifier :hasSubclassifier ?subclassifier .
	?subclassifier :name ?subclassifiername .
	?classifier :name ?classifiername .
	?superclassifier :name ?superclassifiername .
}