PREFIX : <http://myWikiTax.de/>
SELECT DISTINCT ?classifier ?name (COUNT(?dclassifier) as ?howManyDistantTypes) (COUNT(?rclassifier) as ?howManyReachableTypes)
WHERE {
   ?classifier :name ?name.
   ?classifier :isA* ?root.
   ?root :name "Computer_languages".

   NOT EXISTS { ?classifier :marked ?m}.
   FILTER NOT EXISTS {
      ?c2 :isA ?classifier.
      ?c2 :marked ?mark.
   }.

   {SELECT DISTINCT ?classifier ?dclassifier
   WHERE {
       ?classifier :hasCategory ?dclassifier .
       FILTER NOT EXISTS{
           ?classifier :isA ?classifier2 .
           ?classifier2 :name ?dclassifier .
     }

   }}
   UNION
   {SELECT DISTINCT ?classifier ?rclassifier
   WHERE {
       ?classifier :hasCategory ?rclassifier .
       ?classifier :isA ?classifier2 .
       ?classifier2 :name ?rclassifier .
   }}

}
GROUP BY ?name ?classifier
ORDER BY ASC (?name)
