PREFIX : <http://myWikiTax.de/>
SELECT DISTINCT ?classifier ?name ?depth
WHERE {
	?classifier :name ?name.
	?classifier :isA* ?root.
	?root :name "Computer_languages".
   ?classifier :depth ?depth.
	FILTER regex(str(?classifier), "Classifier").
}
ORDER BY DESC (?depth)
