PREFIX : <http://myWikiTax.de/>
SELECT DISTINCT ?n ?t ?f
WHERE {
	?i :instanceOf ?c .
	?i :name ?n.
	?i :hasText ?t.
	?i :firstParagraph ?f.
	?root :name "Computer_languages".
	?c :isA* ?root.
	FILTER regex(str(?i), "Instance")
}
