PREFIX : <http://myWikiTax.de/> 
SELECT DISTINCT ?name ?text ?first
WHERE {
	?l1 :instanceOf ?type3 .
    ?type :isA ?type2 . 
    ?l1 :name ?name .
    ?type :name ?name .
	?l1 :hasText ?text .
	?l1 :firstParagraph ?first.
}
ORDER BY ASC (?depth)