PREFIX : <http://myWikiTax.de/> 
SELECT DISTINCT ?o ?d
WHERE {
    ?c1 :name "Programming languages" .
    ?c3 :name "MATLAB" .
    ?c1 :hasSubclassifier ?c2 .
    ?c2 :hasSubclassifier*/:classifies ?c3 .
    ?c2 :depth ?d .
    ?c2 :name ?o .
}
ORDER BY ASC (?d)