PREFIX : <http://myWikiTax.de/> 
SELECT DISTINCT ?over
WHERE {
    ?c1 :name "Free software programmed in OCaml" .
    ?c1 (:hasSubclassifier)*/:classifies* ?c3 .
    ?c3 :name "MLDonkey" .
    ?c3 :name ?over .
}
