PREFIX : <http://myWikiTax.de/>
SELECT DISTINCT ?name
WHERE {
   ?instance :instanceOf ?c.
   FILTER EXISTS {
      ?c :isA* ?root.
      ?root :name "Computer_languages".
      ?instance :name ?name.
   }
   FILTER EXISTS {
      ?instance :relevant "false".
   }
   FILTER regex(str(?instance), "Instance")
}
