PREFIX : <http://myWikiTax.de/>
SELECT DISTINCT ?instance ?name
WHERE {
	?instance :instanceOf ?c.
	?c :isA* ?root.
	?root :name "Computer_languages".
	?instance :name ?name.
	FILTER regex(str(?instance), "Instance")
}
